### ISSUE TITLE
How to let UITableView focus on to the first visible UITableViewCell instead of the first UITableViewCell?

### ISSUE THREAD

**Issue by piaojin** [dequelabs/Deque-University-for-iOS#45]
### Inaccessible Behavior

* When I put VoiceOver focus on navigation title
* Then swipe right
* Focus moves to the first cell of the tableView, instead of the current visible cell.

### Accessible Behavior
Focus should moves to the current visible cell of the tableView.

### This is my demo
[TableViewInCellDemo 2.zip](https://github.com/dequelabs/Deque-University-for-iOS/files/2509850/TableViewInCellDemo.2.zip)

**Comment by chriscm2006** [comment]
Solved in #42

**Comment by piaojin** [comment]
It since that the solution of #42 is not suited for this question. Please check it! @chriscm2006
