### ISSUE TITLE
Back to trigger issues

### ISSUE THREAD

**Issue by piaojin** [dequelabs/Deque-University-for-iOS#46]
Back to trigger issues.

There are a system back leftBarButton, titleView and a share rightBarButton in the navigationItem.

### Correct behavior
* 1. The system share panel will show after clicking the share rightBarButton.
* 2. The system share panel will dismiss after clicking the cancel button. We use `UIAccessibilityPostNotification` to let the system focus on the share rightBarButton. And it works fine.

### Incorrect behavior
* 1. The system share panel will show after clicking the share rightBarButton.
* 2. In this case, we click the system "Add to Notes" item. And then the system notes is shown.
* 3. We dismiss the system notes app and we use `UIAccessibilityPostNotification` to let the system focus on the share rightBarButton. But the system will focus on the back barButton for the first and read out "back button". And then focus on the share rightBarButton. This is incorrect behavior.

> ### The following is demo:
[HelloGoodbyeUsingtheAccessibilityAPItoWidenYourUserBase.zip](https://github.com/dequelabs/Deque-University-for-iOS/files/2514028/HelloGoodbyeUsingtheAccessibilityAPItoWidenYourUserBase.zip)

**Comment by chriscm2006** [comment]
@piaojin I do not have a system "Add to Notes" button. Is the behavior similar to this? Am I on the correct screen?

![screen shot 2018-10-29 at 10 41 27 am](https://user-images.githubusercontent.com/3856068/47657337-40cb9b80-db67-11e8-8170-b08ff54c8360.png)

**Comment by piaojin** [comment]
@chriscm2006 You can use download the notes app from app store. The notes app is Apple's app. Or you can use high version iPhone to test it.
![img_3c7ef0b092c0-1](https://user-images.githubusercontent.com/10163672/47698361-0686fa80-dc4a-11e8-9d74-5e60628a569c.jpeg)

Sorry, but when will you find a good solution? If you have a good solution please tell me. Thank you!
