### ISSUE TITLE
Using Attest iOS HTTP Service with Unit Tests

### ISSUE THREAD

**Issue by nmashni** [dequelabs/Deque-University-for-iOS#52]
Using Attest iOS HTTP Service with Unit Tests

Thank you, that link indeed works and its VERY helpful.

I can see this being the way that Developers and QA approach accessibility issues, here they can find exactly the troubly elements:
![image001](https://user-images.githubusercontent.com/32878595/48204281-6e6ace80-e337-11e8-8c91-17170fed4a8e.jpg)

I was actually looking for one that generates the same results but in a JSON structure which I can then parse and use for our CI/CD pipeline. (Now with the full version)

Found it!

<img width="789" alt="image002" src="https://user-images.githubusercontent.com/32878595/48204295-73c81900-e337-11e8-9573-4c34da1aeb0b.png">

Which outputs something like this:

![image003](https://user-images.githubusercontent.com/32878595/48204317-7dea1780-e337-11e8-92d7-a192af710549.jpg)

With this, probably at a later stage, we can automate the creation Jira tickets for accessibility defects and be very specific about the elements and fixes required.

--

I do still have a small hiccups I’ll need your help with.

I got this result while going to that link while using the app, meaning I was actually running it and going to those screens. (the HTTP Service was running)

How can I get these results for the tests we added to our Unit tests instead of only the current active screen? In this case the HTTP Service is terminated after the tests are ran.

**Comment by chriscm2006** [comment]
![screen shot 2018-11-08 at 9 45 31 am](https://user-images.githubusercontent.com/3856068/48205986-4d0be180-e33b-11e8-8a82-119fdfa34978.png)

**Comment by chriscm2006** [comment]
The image above highlights this link: https://github.com/dequelabs/Deque-University-for-iOS/blob/master/DequeUniversityForIOSTests/SimpleTest.swift

Getting the results in unit tests is accomplished in a fundamentally different way.

**Comment by chriscm2006** [comment]
Blocked: More info needed or potentially resolved and needs closed.

**Comment by nmashni** [comment]
Sorry I think I wasn’t able to express my question clearly.

 

If you notice, I already hyperlinked to the link you sent me on my previous email.

 

I’m able to get the JSON generated report while running and while the app is active on a specific screen. Our Unit Tests (not to be confused with UI Tests), don’t go through those screens.

 

What I want to know is how to generate the JSON report from the Unit Tests we have. Meaning, from the errors generated in our Unit Tests

**Comment by jldailey13** [comment]
There is a function available for the `Attest.Result` class called `toAxeResult()` that converts the Result structure into a JSON structure that can be parsed in Swift.  It looks identical to the JSON result structure found in `/api/axe_results`.  An example of how it would be used:
```Swift
var json: [ String : Any ] = [:]
Attest.that(storyBoardName: "Main").isAccessible({ result in 
    json = result.toAxeResult()
})
```

@chriscm2006 we may want to add this to documentation.

**Comment by chriscm2006** [comment]
Ah, I see. I think the customer is looking for the `toAxeResult` function.

```
Attest.that(storyBoardName: "ConflictingTraits").isAccessible({(result:AttestResult) -> () in
    let json = try? JSONSerialization.jsonObject(with: result.toAxeResult(), options: [])
    print(json)
})
```

See if this resolves their problem issue.

**Comment by chriscm2006** [comment]
Baha! Jennifer's answer is prettier... go with that, but we're saying the same thing.

**Comment by jldailey13** [comment]
I mean, my answer doesn't actually convert it to JSON, it just converts it to structure that can be converted to JSON (or used in Swift).

**Comment by nmashni** [comment]
Thanks, I sent these suggestions to the customer and will let you know what comes of it.

**Comment by chriscm2006** [comment]
The problem with your answer, is a developer would normally assume a variable named "json" is a string. The perfect answer would be converting to a dictionary first, and then to json. Letting the developer pick which they want.
